# Site settings
title: snakelab
email: max.nedelchev@gmail.com
paginate: 6
paginate_path: "/page/:num"
description: > # this means to ignore newlines until "baseurl:"
  my two cents about the life
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://snakelab.cc" # the base hostname & protocol for your site


github_username:  ssnake
facebook: max.nedelchev

# Build settings
markdown: kramdown
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace",
 "test", "CNAME", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
sass:
  sass_dir: _scss
gems: [jekyll-paginate]