# Site settings
title: snakelab
email: max.nedelchev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  the place where my work lives
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://snakelab.cc" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  ssnake

# Build settings
markdown: redcarpet
